### ISSUE TITLE
Running with Raspian / Mono

### ISSUE THREAD

**Issue by moelski** [emmellsoft/RPi.SenseHat#7]
Hi !

Do you think this would also run (with some small modifications) on Raspian + Mono? 
What problems could exists? 

Dominik

**Comment by emmellsoft** [comment]
Hi Dominik!
It should be doable! The code is written for Windows UWP, so there are a number of things that must be somewhat rewritten using other libraries.
The biggest issue might be to replace the I2C-library. (A quick googling gave https://github.com/mshmelev/RPi.I2C.Net -- maybe it's useful?)
Then there's the `Color`-struct (small issue) and the `PixelSupport.GetPixels(Uri imageUri)` method (not vital, it may be removed; otherwise totally rewritten). Apart from that maybe the `async` things might need some changes (maybe not?), but that is not used very extensively anyway.
The demo code must obviously be rewritten, since it's living inside XAML-based UWP forms.
Conclusion: if you get the I2C to work then you're home free! :-)
Good luck -- tell me if you need some assistance!
